# Generated by Django 5.1.7 on 2025-03-26 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0002_alter_task_task_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('feature', 'Feature'), ('bugfix', 'Bug Fix'), ('enhancement', 'Enhancement'), ('documentation', 'Documentation'), ('research', 'Research'), ('testing', 'Testing'), ('deployment', 'Deployment'), ('maintenance', 'Maintenance'), ('optimization', 'Optimization'), ('security', 'Security Update'), ('refactor', 'Code Refactor'), ('support', 'Customer Support')], default='feature', max_length=20),
        ),
    ]
