# Generated by Django 5.1.7 on 2025-03-26 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0003_task_priority_alter_task_task_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='assigned_users',
            field=models.ManyToManyField(related_name='assigned_tasks', to='task_manager.user'),
        ),
    ]
