"""
Django settings for task_management project.

Generated by 'django-admin startproject' using Django 4.2.10.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
import os
from pathlib import Path
from dotenv import load_dotenv

# Load environment variables from .env
load_dotenv()


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY')
DEBUG = os.getenv('DEBUG', 'False') == 'True'
ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS').split(',')


# Application definition

INSTALLED_APPS = [
    'social_django',
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'task_manager',
    'drf_yasg',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
'social_django.middleware.SocialAuthExceptionMiddleware',  # ✅ Add this
]

ROOT_URLCONF = 'task_management.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'task_management.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases
#
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.' + os.getenv('DB_ENGINE', 'mysql'),
        'NAME': os.getenv('DB_NAME'),
        'USER': os.getenv('DB_USER'),
        'PASSWORD': os.getenv('DB_PASSWORD'),
        'HOST': os.getenv('DB_HOST'),
        'PORT': os.getenv('DB_PORT'),
    }
}
# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
SITE_ID = 1  # Default site
# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = os.getenv('GOOGLE_CLIENT_ID')  # Client ID
SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = os.getenv('GOOGLE_CLIENT_SECRET')  # Client Secret

# For allauth (if you're using it)
GOOGLE_CLIENT_ID = os.getenv('GOOGLE_CLIENT_ID')
GOOGLE_CLIENT_SECRET = os.getenv('GOOGLE_CLIENT_SECRET')
GOOGLE_REDIRECT_URI = "http://127.0.0.1:8000/google/callback/"

# Social Auth Settings

SOCIAL_AUTH_GOOGLE_OAUTH2_REDIRECT_URI = GOOGLE_REDIRECT_URI
SOCIAL_AUTH_GOOGLE_OAUTH2_SCOPE = ['email', 'profile']

# Directory where static files will be collected
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Django Authentication Settings
AUTHENTICATION_BACKENDS = (
    'social_core.backends.google.GoogleOAuth2',  #  Required for Google OAuth
    'django.contrib.auth.backends.ModelBackend',  #  Default auth backend
)
# Login/Logout Redirect URLs


LOGIN_REDIRECT_URL = "/choose-redirect/"
# LOGOUT_REDIRECT_URL = "/"
LOGOUT_REDIRECT_URL = '/logout/'
SOCIAL_AUTH_ASSOCIATE_BY_EMAIL = True

JAZZMIN_SETTINGS = {
    "site_title": "Task Management Admin",
    "site_header": "Task Management",
    "site_brand": "Task Management",
    "welcome_sign": "Welcome to Task Management Admin",

    "copyright": "© 2025 Task Management",
    "search_model": ["auth.User", "task_management.Task"],  # Search functionality

    # Theme Customization
    "theme": "cyborg",  # Options: flatly, darkly, solar, lumen, pulse, cyborg, etc.
    "show_ui_builder": True,  # Hide UI Customization Builder
    "changeform_format": "horizontal_tabs",  # Beautiful horizontal tabbed forms
    "changeform_format_overrides": {
        "auth.user": "collapsible",  # Collapsible sections for user forms
        "task_management.Task": "vertical_tabs",  # Vertical tab layout for tasks
    },

    # Sidebar Customization
    "navigation_expanded": False,  # Sidebar stays collapsed by default
    "order_with_respect_to": ["auth", "task_management", "task_management.Task"],  # Sidebar menu order
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
        "task_management.Task": "fas fa-tasks",
        "task_management.Assignment": "fas fa-user-check",
    },

    # Custom Links
    "custom_links": {
        "auth": [{
            "name": "Custom User Action",
            "url": "admin:auth_user_changelist",
            "icon": "fas fa-user-shield",
            "permissions": ["auth.view_user"]
        }],
    },

}